# Generated by Django 4.1.2 on 2022-12-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_uploadimage_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='images/nou'),
        ),
    ]
