# Generated by Django 4.1.2 on 2022-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='C:/Users/andre/Desktop/ASO/Project'),
        ),
    ]
